---
- name: Clone theme repository
  ansible.builtin.git:
    repo: "{{ theme_repo }}"
    dest: "/home/{{ ohmyzsh_user }}/theme"
    update: no
  become_user: "{{ ohmyzsh_user }}"
  when: install_theme

- name: Copy p10k.zsh theme config file
  ansible.builtin.copy:
    src: "files/p10k.zsh"
    dest: "/home/{{ ohmyzsh_user }}/.p10k.zsh"
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: "0644"
  when: install_theme

- name: Create fonts directory if not exists
  ansible.builtin.file:
    path: "/home/{{ ohmyzsh_user }}/.local/share/fonts"
    state: directory
    owner: "{{ ohmyzsh_user }}"
    group: "{{ ohmyzsh_user }}"
    mode: "0755"
  become: true

- name: Download fonts for powerlevel10k theme (Regular)
  ansible.builtin.get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
    dest: "/home/{{ ohmyzsh_user }}/.local/share/fonts/MesloLGS NF Regular.ttf"
    mode: "0644"
  become: true

- name: Download fonts for powerlevel10k theme (Bold)
  ansible.builtin.get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
    dest: "/home/{{ ohmyzsh_user }}/.local/share/fonts/MesloLGS NF Bold.ttf"
    mode: "0644"
  become: true

- name: Download fonts for powerlevel10k theme (Italic)
  ansible.builtin.get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
    dest: "/home/{{ ohmyzsh_user }}/.local/share/fonts/MesloLGS NF Italic.ttf"
    mode: "0644"
  become: true

- name: Download fonts for powerlevel10k theme (Bold Italic)
  ansible.builtin.get_url:
    url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
    dest: "/home/{{ ohmyzsh_user }}/.local/share/fonts/MesloLGS NF Bold Italic.ttf"
    mode: "0644"
  become: true
