---
- name: Remove unwanted packages
  ansible.builtin.dnf:
    name: "{{ remove_dnf_packages_work }}"
    state: absent
  become: true

- name: Update DNF package cache
  ansible.builtin.dnf:
    update_cache: true
  become: true

- name: Upgrade all installed packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
  become: true

- name: Install additional packages
  ansible.builtin.dnf:
    name: "{{ dnf_packages_work }}"
    state: present
  become: true
